[build]
  command = "npm run build"

 [build.environment]
   NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = ".netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-nextjs"
